import { Inter } from "next/font/google";
import "./globals.css";

import {
	Menubar,
	MenubarContent,
	MenubarItem,
	MenubarMenu,
	MenubarSeparator,
	MenubarShortcut,
	MenubarTrigger,
} from "@/components/ui/menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Next Movie",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="container mt-4">
					<Menubar>
						<h1 className="mx-4">Next Movie</h1>
					</Menubar>

					<main className="mt-4">{children}</main>
				</div>
			</body>
		</html>
	);
}
