import { Inter } from "next/font/google";
import "./globals.css";

import { Menubar } from "@/components/ui/menubar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Next Movie",
	description: "Generated by create next app",
};

const token = process.env.TOKEN;

async function fetchGenres() {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
		headers: {
			Authorization: `Bearer ${token}`,
		},
	});

	return await res.json();
}

export default async function RootLayout({ children }) {
	const data = await fetchGenres();

	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="container mt-4">
					<Menubar>
						<h1 className="mx-4">Next Movie</h1>
					</Menubar>

					<main className="mt-4">
						<div className="flex">
							<div className="pr-4 border-r w-[250px]">
								<Button
									variant="ghost"
									className="justify-start">
									<Link
										href="/"
										className="flex items-center gap-2">
										<svg
											width="15"
											height="15"
											viewBox="0 0 15 15"
											fill="none"
											xmlns="http://www.w3.org/2000/svg">
											<path
												d="M3.24182 2.32181C3.3919 2.23132 3.5784 2.22601 3.73338 2.30781L12.7334 7.05781C12.8974 7.14436 13 7.31457 13 7.5C13 7.68543 12.8974 7.85564 12.7334 7.94219L3.73338 12.6922C3.5784 12.774 3.3919 12.7687 3.24182 12.6782C3.09175 12.5877 3 12.4252 3 12.25V2.75C3 2.57476 3.09175 2.4123 3.24182 2.32181ZM4 3.57925V11.4207L11.4288 7.5L4 3.57925Z"
												fill="currentColor"
												fill-rule="evenodd"
												clip-rule="evenodd"></path>
										</svg>
										All Movies
									</Link>
								</Button>
								{data.genres.map(genre => {
									return (
										<Button
											key={genre.id}
											variant="ghost"
											className="w-full justify-start gap-2">
											<Link
												href={`/genres/${genre.name}/${genre.id}`}
												className="flex items-center gap-2">
												<svg
													width="15"
													height="15"
													viewBox="0 0 15 15"
													fill="none"
													xmlns="http://www.w3.org/2000/svg">
													<path
														d="M3.24182 2.32181C3.3919 2.23132 3.5784 2.22601 3.73338 2.30781L12.7334 7.05781C12.8974 7.14436 13 7.31457 13 7.5C13 7.68543 12.8974 7.85564 12.7334 7.94219L3.73338 12.6922C3.5784 12.774 3.3919 12.7687 3.24182 12.6782C3.09175 12.5877 3 12.4252 3 12.25V2.75C3 2.57476 3.09175 2.4123 3.24182 2.32181ZM4 3.57925V11.4207L11.4288 7.5L4 3.57925Z"
														fill="currentColor"
														fill-rule="evenodd"
														clip-rule="evenodd"></path>
												</svg>
												{genre.name}
											</Link>
										</Button>
									);
								})}
							</div>

							<div className="pl-4">{children}</div>
						</div>
					</main>
				</div>
			</body>
		</html>
	);
}
